[project]
name = "pandemic-control"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13, <=3.14"
dependencies = [
    "audioop-lts",
    "gymnasium",
    "ipykernel",
    "jupyter",
    "lab",
    "loguru",
    "matplotlib",
    "numpy",
    "pandas",
    "rich",
    "sb3-contrib",
    "scipy",
    "seaborn",
    "stable-baselines3",
    "tbparse",
    "tensorboard",
    "torch==2.12.1",
    "torchvision==0.27.1",
    "tqdm",
    "wandb",
]

[tool.uv.sources]
torch = {index = "pytorch-cu132", marker = "sys_platform == 'linux'"}
torchvision = {index = "pytorch-cu132", marker = "sys_platform == 'linux'"}
torchaudio = {index = "pytorch-cu132", marker = "sys_platform == 'linux'"}


[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"

# Configuration for uv
[tool.uv]
index-strategy = "unsafe-best-match" # Crucial for resolving complex dependency conflicts

[tool.setuptools.packages.find]
    where = ["."] # Search in the current directory
    include = ["pandemic_control"] # Include packages starting with these names
